runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

env_variables:
  CLOUDSQL_CONNECTION_NAME: little-facebook:us-east1:db0
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: renegade

libraries:
- name: MySQLdb
  version: "latest"
